#!/usr/bin/env bash
# This script run Nginx as Nginx to prevent the impact is limited by the permissions of the nginx user
sudo chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx stop
sudo -u nginx service nginx start"
 https://github.com/luismch158158/holbertonschool-system_engineering-devops/blob/master/0x12-web_stack_debugging_2/100-fix_in_7_lines_or_less#:~:text=%23!/usr/bin,service%20nginx%20start
